#!/usr/bin/env bash
# Render Formula/codex-shake.rb for the epsalmond/homebrew-codex-shake tap
# and print it on stdout.
#
#   render-brew-formula.sh <release-tag> <source-version> \
#     <darwin-arm64-sha256> <linux-x86_64-sha256>
#
# <release-tag>          e.g. local-features-v0.154.0-main-r20260914110830.<sha>
#                         or local-features-v0.154.0-r202609140816.<sha>
# <source-version>        workspace Cargo version, e.g. 0.154.0
# <darwin-arm64-sha256>   sha256 of codex-aarch64-apple-darwin.tar.gz
# <linux-x86_64-sha256>   sha256 of codex-x86_64-unknown-linux-gnu.tar.gz
set -euo pipefail

usage() {
  echo "usage: render-brew-formula.sh <release-tag> <source-version> <darwin-arm64-sha256> <linux-x86_64-sha256>" >&2
}

[[ $# -eq 4 ]] || { usage; exit 2; }

release_tag=$1
source_version=$2
darwin_sha=$3
linux_sha=$4

if [[ "$release_tag" =~ -r([0-9]{1,14})\.([0-9a-fA-F]+)$ ]]; then
  counter="${BASH_REMATCH[1]}"
  sha="${BASH_REMATCH[2]}"
else
  echo "render-brew-formula: could not parse counter/sha from release tag: $release_tag" >&2
  exit 1
fi

[[ "$darwin_sha" =~ ^[0-9a-fA-F]{64}$ ]] || {
  echo "render-brew-formula: darwin sha256 does not look like a sha256: $darwin_sha" >&2
  exit 1
}
[[ "$linux_sha" =~ ^[0-9a-fA-F]{64}$ ]] || {
  echo "render-brew-formula: linux sha256 does not look like a sha256: $linux_sha" >&2
  exit 1
}

# Never include the sha in the formula version -- Homebrew treats
# non-numeric-dotted suffixes awkwardly for upgrade comparisons, and the tag
# plus sha are enough provenance in a comment.
formula_version="${source_version}.${counter}"

cat <<RUBY
# frozen_string_literal: true

# Generated by epsalmond/codex .github/scripts/render-brew-formula.sh.
# Do not hand-edit: this file is overwritten by codex-fork-release CI on
# every published eric/local-features release.
#
# Source release: ${release_tag}
# Source commit (short): ${sha}
class CodexShake < Formula
  desc "Eric/local-features fork build of Codex CLI, as codex-shake"
  homepage "https://github.com/epsalmond/codex"
  version "${formula_version}"
  license "Apache-2.0"

  livecheck do
    skip "tap is updated by epsalmond/codex CI"
  end

  on_macos do
    on_arm do
      url "https://github.com/epsalmond/codex/releases/download/${release_tag}/codex-aarch64-apple-darwin.tar.gz"
      sha256 "${darwin_sha}"
    end
    on_intel do
      odie "codex-shake has no x86_64 macOS build"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/epsalmond/codex/releases/download/${release_tag}/codex-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_sha}"
    end
    on_arm do
      odie "codex-shake has no aarch64 Linux build"
    end
  end

  def install
    libexec.install Dir["*"]
    (bin/"codex-shake").write_env_script libexec/"codex", PATH: "#{libexec}:\$PATH"
    return unless File.exist?(libexec/"codex-shake-estimate")

    (bin/"codex-shake-estimate").write_env_script libexec/"codex-shake-estimate", PATH: "#{libexec}:\$PATH"
  end

  test do
    assert_match(/\d+\.\d+\.\d+/, shell_output("#{bin}/codex-shake --version"))
  end
end
RUBY
