// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether this root backend can provide authoritative work observation.
 */
export type ThreadWorkSubscribeOutcome = "subscribed" | "unavailable";
