// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Child agent results held by an interrupted thread until its next user message.
 */
export type ThreadWakeupsUpdatedNotification = { threadId: string,
/**
 * Whether automatic wakeups from child results are paused until the next user message.
 */
paused: boolean,
/**
 * Child results that the next user turn will carry.
 */
queuedResults: number, };
