// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextReduction } from "./ThreadContextReduction";
import type { ThreadContextTokenBasis } from "./ThreadContextTokenBasis";

/**
 * Context and policy of a captured prepared request, separate from cumulative usage.
 */
export type ThreadContextUsage = { activeTokens: number, basis: ThreadContextTokenBasis, lastReduction: ThreadContextReduction | null, selectedModel: string | null, childPolicyEnabled: boolean | null, childActiveCapTokens: number | null, modelWindowTokens: number | null, observedAt: number | null, providerUsageAt: number | null,
/**
 * Exclusive sealed-history-item boundary, not tokens or a percentage.
 */
shakeWatermark: number | null, };
