// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextReductionOutcome } from "./ThreadContextReductionOutcome";

export type ThreadContextReduction = { completedAt: number, beforeTokens: number, afterTokens: number | null, outcome: ThreadContextReductionOutcome, };
