// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadShakeStartParams = { threadId: string,
/**
 * Surgical context-reduction mode: "elide" | "smartCompact" | "images" | "thinking".
 */
mode: string,
/**
 * Fingerprint returned by a preview; omit to apply without a preview.
 */
expectedFingerprint?: string | null, };
