// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadWorkSnapshot } from "./ThreadWorkSnapshot";

/**
 * Lifecycle snapshot published when observed root work changes.
 */
export type ThreadWorkUpdatedNotification = { threadId: string, snapshot: ThreadWorkSnapshot, };
