// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bounded snapshot of work owned by one root thread.
 */
export type ThreadWorkSnapshot = {
/**
 * Opaque coordinator-incarnation and revision token. Pass it back unchanged to guard close.
 */
revision: string, outstandingWork: number, runningFiniteWork: number, pendingNotifications: number, activeRootTurns: number, pendingTerminalOutputs: number, outputForwardingObserved: boolean, closed: boolean, quiescent: boolean, };
