// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Possible outcomes of `thread/shutdownIfQuiescent`.
 */
export type ThreadWorkShutdownOutcome = "closed" | "alreadyClosed" | "observationInactive" | "staleRevision" | "notQuiescent";
