// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShakePreview = {
/**
 * Opaque identifier of the history and mode measured by this preview.
 */
fingerprint: string,
/**
 * Approximate conversation tokens, excluding tool schemas and base instructions.
 */
tokensBefore: number, tokensAfter: number, toolOutputs: number, textBlocks: number, images: number, thinkingBlocks: number,
/**
 * Present when this mode cannot be applied to the current thread.
 */
unavailableReason: string | null, };
